CAV-127: Phone Validation & Verification Error Handling
hmrc/cip-phone-number-verification pull request #30
Opened 2022-09-07 14:07 UTC by johno1985

- return 503 when connection exception occurs

2022-09-07 14:47 UTC, mar36tin approved these changes

2022-09-07 14:47 UTC, mar36tin requested changes
Tests failing

2022-09-07 14:48 UTC, johno1985 commented
Yep, I believe I need to rebase your CAV-163 changes for them to pass

2022-09-09 14:10 UTC, mar36tin approved these changes

2022-09-13 09:10 UTC, merged