Cav 444
hmrc/cip-phone-number-verification pull request #40
Opened 2022-10-06 14:58 UTC by mar36tin

2022-10-06 16:16 UTC, brdgeth submitted a review, later dismissed

2022-10-07 12:51 UTC, johno1985 commented on app/uk/gov/hmrc/cipphonenumberverification/services/PasscodeService.scala
> +    logger.debug(s"Storing phoneNumberAndPasscode in database for ${phoneNumberAndPasscode.phoneNumber}")
drop this as it is PII

2022-10-07 12:52 UTC, johno1985 commented on app/uk/gov/hmrc/cipphonenumberverification/services/PasscodeService.scala
> +    logger.debug(s"Retrieving phoneNumberAndPasscode from database for $phoneNumber")
and this, PII

2022-10-07 12:52 UTC, johno1985 commented on app/uk/gov/hmrc/cipphonenumberverification/services/VerifyHelper.scala
> +        println(savedPhoneNumberPasscodeData)
left by mistake?

2022-10-07 12:56 UTC, johno1985 requested changes
minor comments

2022-10-07 13:06 UTC, johno1985 approved these changes

2022-10-07 13:07 UTC, merged